@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Server.Main",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_106069776 { 
   	label=other
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Serializer1939485593[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Serializer</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ deserialize(bytes: byte[]): Object</TD></TR>
<TR><TD ALIGN="LEFT" >+ serialize(object: Object): byte[]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1201883001 { 
   	label=command_processing
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   ClientCommandProcessor1987040106[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ClientCommandProcessor</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   commandMap: HashMap&lt;String, Command&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   inputStream: InputStream [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ processCommand(command: Command): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ processLine(line: String): Optional&lt;Command&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CommandProcessor1630408848[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CommandProcessor</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   inputStream: InputStream [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ printResult(result: ResultDTO)</TD></TR>
<TR><TD ALIGN="LEFT" >+ processCommand(command: Command): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ processLine(line: String): Optional&lt;Command&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ processStream(inStream: InputStream): ArrayList&lt;Command&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ServerCommandProcessor526726386[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ServerCommandProcessor</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   collection: AbstractRouteCollection [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   commandMap: HashMap&lt;String, Command&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ processClientBytes(serializedCommand: byte[]): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ processCommand(command: Command): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ processLine(line: String): Optional&lt;Command&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

YamlTools526726386[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)YamlTools</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ load(fileName: String): HashMap&lt;Integer, Route&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ save(collection: HashMap&lt;Integer, Route&gt;, fileName: String): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1821959325 { 
   	label=Server
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Main1821959325[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Main</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1933991036 { 
   	label=client_commands
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   ExecuteFile1438325639[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ExecuteFile</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   commands: ArrayList&lt;Command&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fileName: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   inputStream: InputStream [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(collection: AbstractRouteCollection): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ setStream(inStream: InputStream): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ validate(args: String[]): ResultDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1983070683 { 
   	label=resources
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   AbstractRouteCollection272336892[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AbstractRouteCollection</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   collection: HashMap&lt;Integer, Route&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >+   initTime: Long [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ clear()</TD></TR>
<TR><TD ALIGN="LEFT" >+ get(key: int): Route</TD></TR>
<TR><TD ALIGN="LEFT" >+ put(key: int, route: Route)</TD></TR>
<TR><TD ALIGN="LEFT" >+ remove(id: int): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ size(): int</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

RouteBuilder272336892[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)RouteBuilder</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   buff: Object [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   description: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   descriptionIndex: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   error: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fieldRequirments: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fieldType: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   lineReader: Scanner [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ build(): Route</TD></TR>
<TR><TD ALIGN="LEFT" >- createCoords(): Coordinates</TD></TR>
<TR><TD ALIGN="LEFT" >- createDistance(): Integer</TD></TR>
<TR><TD ALIGN="LEFT" >- createDouble(canBeNull: boolean): Double</TD></TR>
<TR><TD ALIGN="LEFT" >- createFloat(canBeNull: boolean): Float</TD></TR>
<TR><TD ALIGN="LEFT" >- createInt(canBeNull: boolean): Integer</TD></TR>
<TR><TD ALIGN="LEFT" >- createLocation(canBeNull: boolean): Location</TD></TR>
<TR><TD ALIGN="LEFT" >- createString(canBeEmpty: boolean): String</TD></TR>
<TR><TD ALIGN="LEFT" >- nextDescription()</TD></TR>
<TR><TD ALIGN="LEFT" >- prevDescription()</TD></TR>
<TR><TD ALIGN="LEFT" >- readInputLine(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2021122027 { 
   	label=Client
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   NetworkTools2021122027[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)NetworkTools</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- packetSampling(payload: byte[])</TD></TR>
<TR><TD ALIGN="LEFT" >+ receiveAnswer(): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >- receivePacket(container: byte[], offset: int): byte[]</TD></TR>
<TR><TD ALIGN="LEFT" >+ sendCommand(command: Command, port: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ sendCommand(command: Command): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2048124298 { 
   	label=network_modules
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   ConnectionManager262401515[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ConnectionManager</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   buffer: ByteBuffer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   channel: DatagramChannel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   port: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   requests: HashMap&lt;SocketAddress, byte[]&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ answerClient(address: SocketAddress, message: ResultDTO)</TD></TR>
<TR><TD ALIGN="LEFT" >- connect(port: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getRequestBytes(address: SocketAddress): byte[]</TD></TR>
<TR><TD ALIGN="LEFT" >- increaseBufferSize(size: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ increaseByteArray(array: byte[], newLength: int): byte[]</TD></TR>
<TR><TD ALIGN="LEFT" >- packetSampling(address: SocketAddress, message: byte[])</TD></TR>
<TR><TD ALIGN="LEFT" >- receiveData(): byte[]</TD></TR>
<TR><TD ALIGN="LEFT" >+ receiveNextPacket(): SocketAddress</TD></TR>
<TR><TD ALIGN="LEFT" >+ reconnect()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_602535288 { 
   	label=commands
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   CheckIdExists1548429777[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CheckIdExists</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   id: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(collection: AbstractRouteCollection): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ validate(args: String[]): ResultDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CheckKeyExists1548429777[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CheckKeyExists</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   key: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(collection: AbstractRouteCollection): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ validate(args: String[]): ResultDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Clear1548429777[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Clear</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(collection: AbstractRouteCollection): ResultDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ContainsName1548429777[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ContainsName</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(collection: AbstractRouteCollection): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ validate(args: String[]): ResultDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Exit1548429777[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Exit</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(collection: AbstractRouteCollection): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ validate(args: String[]): ResultDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Help1548429777[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Help</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(collection: AbstractRouteCollection): ResultDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Info1548429777[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Info</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(collection: AbstractRouteCollection): ResultDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Insert1548429777[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Insert</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   key: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   route: Route [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(collection: AbstractRouteCollection): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ setObject(obj: Object): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ validate(args: String[]): ResultDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PrintUniqueDistance1548429777[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PrintUniqueDistance</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(collection: AbstractRouteCollection): ResultDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

RemoveByKey1548429777[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)RemoveByKey</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   key: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(collection: AbstractRouteCollection): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ validate(args: String[]): ResultDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

RemoveGreater1548429777[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)RemoveGreater</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   route: Route [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(collection: AbstractRouteCollection): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ setObject(obj: Object): ResultDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

RemoveGreaterKey1548429777[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)RemoveGreaterKey</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   key: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(collection: AbstractRouteCollection): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ validate(args: String[]): ResultDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ReplaceLower1548429777[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ReplaceLower</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   key: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   route: Route [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(collection: AbstractRouteCollection): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ setObject(obj: Object): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ validate(args: String[]): ResultDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Save1548429777[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Save</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   fileName: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(collection: AbstractRouteCollection): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ validate(args: String[]): ResultDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Show1548429777[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Show</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(collection: AbstractRouteCollection): ResultDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

StartsWithName1548429777[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)StartsWithName</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(collection: AbstractRouteCollection): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ validate(args: String[]): ResultDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UpdateById1548429777[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UpdateById</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   id: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   route: Route [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ execute(collection: AbstractRouteCollection): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ setObject(obj: Object): ResultDTO</TD></TR>
<TR><TD ALIGN="LEFT" >+ validate(args: String[]): ResultDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
ClientCommandProcessor1987040106 -> CheckIdExists1548429777[arrowhead=none];
ClientCommandProcessor1987040106 -> CheckKeyExists1548429777[arrowhead=none];
ClientCommandProcessor1987040106 -> Clear1548429777[arrowhead=none];
ClientCommandProcessor1987040106 -> ContainsName1548429777[arrowhead=none];
ClientCommandProcessor1987040106 -> Exit1548429777[arrowhead=none];
ClientCommandProcessor1987040106 -> Help1548429777[arrowhead=none];
ClientCommandProcessor1987040106 -> Info1548429777[arrowhead=none];
ClientCommandProcessor1987040106 -> Insert1548429777[arrowhead=none];
ClientCommandProcessor1987040106 -> PrintUniqueDistance1548429777[arrowhead=none];
ClientCommandProcessor1987040106 -> RemoveByKey1548429777[arrowhead=none];
ClientCommandProcessor1987040106 -> RemoveGreater1548429777[arrowhead=none];
ClientCommandProcessor1987040106 -> RemoveGreaterKey1548429777[arrowhead=none];
ClientCommandProcessor1987040106 -> ReplaceLower1548429777[arrowhead=none];
ClientCommandProcessor1987040106 -> RouteBuilder272336892[label="processLine() -> build()"];
ClientCommandProcessor1987040106 -> Save1548429777[arrowhead=none];
ClientCommandProcessor1987040106 -> Show1548429777[arrowhead=none];
ClientCommandProcessor1987040106 -> StartsWithName1548429777[arrowhead=none];
ClientCommandProcessor1987040106 -> UpdateById1548429777[arrowhead=none];
CommandProcessor1630408848 -> ClientCommandProcessor1987040106[arrowhead=none, arrowtail=empty, dir=both];
CommandProcessor1630408848 -> ServerCommandProcessor526726386[arrowhead=none, arrowtail=empty, dir=both];
ConnectionManager262401515 -> Serializer1939485593[label="answerClient() -> serialize()"];
Main1821959325 -> CommandProcessor1630408848[label="main() -> printResult()"];
Main1821959325 -> YamlTools526726386[label="main() -> load()"];
ServerCommandProcessor526726386 -> AbstractRouteCollection272336892[label="collection
[0..1]"];
ServerCommandProcessor526726386 -> Serializer1939485593[label="processClientBytes() -> deserialize()"];
    
}
@enduml